name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build site
        run: |
          # Your build commands here, e.g.
          npm install
          npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist  # or ./build or your output folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
